site_name: stock-tech-ichimoku
site_description: Documentation for the stock-tech-ichimoku Python Project
site_author: Mark Quinn
repo_url: https://github.com/finsite/stock-tech-ichimoku
theme:
  name: material

nav:
  - Home: index.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys; sys.path.append('src')

markdown_extensions:
  - admonition
  - toc:
      permalink: true

repo_url: https://github.com/finsite/stock-tech-ichimoku